//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos_Empresas
    {
        public int Id { get; set; }
        public int Producto_Id { get; set; }
        public int Empresa_Id { get; set; }
        public bool Estatus { get; set; }
    
        public virtual Empresas Empresas { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
