//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Ventas = new HashSet<Ventas>();
            this.Compras = new HashSet<Compras>();
        }
    
        public int Id { get; set; }
        public string CorreoElectronico { get; set; }
        public string Password { get; set; }
        public int EmpresaId { get; set; }
        public string Telefono { get; set; }
        public string Nombres { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Activo { get; set; }
        public int Rol_Id { get; set; }
        public string Token { get; set; }
    
        public virtual Catalogos Catalogos { get; set; }
        public virtual Empresas Empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas> Ventas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compras> Compras { get; set; }
    }
}
