//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ventas()
        {
            this.Impuestos = new HashSet<Impuestos>();
        }
    
        public int Id { get; set; }
        public string Venta { get; set; }
        public int Cliente_Id { get; set; }
        public int Producto_Id { get; set; }
        public Nullable<decimal> CostoUnitario { get; set; }
        public Nullable<decimal> CostoTotal { get; set; }
        public Nullable<decimal> CostoNeto { get; set; }
        public Nullable<decimal> GranTotal { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Cantidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Impuestos> Impuestos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
